### ISSUE TITLE
It doesn't for .MOV by default and i cannot change that settings.

### ISSUE THREAD

**Issue by Jazzykhan** [awslabs/video-on-demand-on-aws-foundations#3]
Hi, thanks for this great formation. the problem i am facing is when i upload a .MOV file in source folder the job doesn't start.

**Comment by morjoan** [comment]
Hi there, 
By default, the S3 event notification is configured to trigger the workflow when a video is uploaded with one of the following lowercase file extensions: .mp4, .mpg, .m4v, .m2ts, and .mov.

However, you can do one of the following options to include support for your file extension:
1. If you are comfortable rebuilding the solution, you may customize S3 notification source code to include any file extensions supported by MediaConvert (like .MOV) to trigger the job: https://github.com/awslabs/video-on-demand-on-aws-foundations/blob/main/source/custom-resource/lib/s3/index.js  After you make the changes, rebuild and redeploy the solution.
2. Edit your S3 source bucket's Event Notification to trigger on a .MOV (upper case) extension. See https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-event-notifications.html 
3. Rename your source video file to use the .mov (lower case) extension. 
Hope this gets you going!

**Comment by tomgilman** [comment]
Please open a new issue if the above doesn't work.

**Comment by Foixa** [comment]
I added a new extension, but when I deploy the solution again, this extension is not added to the s3 bucket.
