### ISSUE TITLE
Can't make cloudfront accessible for public (as a test)

### ISSUE THREAD

**Issue by FTBrawner** [awslabs/video-on-demand-on-aws-foundations#5]
Now that I have figured out my video viewing error, I can't figure out why i can't view my cloudfront.  I keep getting:

Error
   CodeAccessDenied/Code
   RequestID gibberish  here /RequestId
   Hostid long gibberish /HostId
/Error

I'm coping the various urls out of cloud front, and trying them through http: and https:  (Had to take the <> out because it inserted it as code)

TIA

**Comment by morjoan** [comment]
Hi, I'm not sure I understand what you mean by "view your CloudFront". It sounds like you were able to view the videos generated by the solution via the CloudFront distribution. Is that correct? 
If you are trying to use your CloudFront distribution for other purposes other than viewing your video content, I suggest checking out the CloudFront developer guide documentation: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html

**Comment by FTBrawner** [comment]
so my issue, is i can put a link in a player (vlc as an example) and it
will play the DASH and/or HLS, but actually viewing my videos as a webpage,
isn't working lol, i know you didn't include that in the solution.  Also,
mediaconvert is rotating my mov (iphone) videos counterclockwise 270, i'm
editing now to add the "Rotate": "AUTO" to the proper buckets and going to
recommit to test
it.
--Felton

**Comment by morjoan** [comment]
As it's outside the scope of the solution, I suggest looking into web video players like Video.js that you can embed into your webpage that has support for HLS and DASH. Hope that points you in the right direction. Good luck!

**Comment by FTBrawner** [comment]
You're great Thank you!

**Comment by tomgilman** [comment]
Closing this issue.
